### ISSUE TITLE
Some ZIP files cause crashes

### ISSUE THREAD

**Issue by TaoK** [notepad-plus-plus/wingup#10]
When including the *Poor Man's T-Sql Formatter* plugin in the plugin admin JSON, I found that my existing ZIP packages caused crashes of GUP.exe (v5.0.5) - after a bunch of head-scratching and trial-and-error, that is. Some kind of UI indicator, when something goes wrong, could be helpful.

I posted in the forum (https://notepad-plus-plus.org/community/topic/16940/gup-exe-crashes-on-some-zip-files-and-http-hosts) and @dinkumoil kindly pointed to existing Issue #7 / #8 and later commit https://github.com/notepad-plus-plus/wingup/commit/dfbc2ad37abe67e0db6844e54d56bf0e423b1f26 in this project - it sounds like my issue is also related to this "unreliable unzip component".

Two important notes:

1. Files that trigger this bug (presumably useful for fixing it) can be found at:
  * http://poorsql.com/TestDL/SqlFormatterNppPlugin.1.6.10.causescrash.zip
  * http://poorsql.com/TestDL/SqlFormatterNppPlugin.x64.1.6.10.causescrash.zip
2. The issue can be **worked around**, at least in my case, by recreating the ZIP file in WinRAR. Unfortunately, I don't remember how I originally created the ZIP files - I suspect the Windows Explorer built-in context menu, but not sure.

**Comment by chcg** [comment]
Issue is probably fixed with: https://github.com/notepad-plus-plus/wingup/releases/tag/v5.1

**Comment by donho** [comment]
Fixed
