### ISSUE TITLE
Use of uninitialized memory?

### ISSUE THREAD

**Issue by Berbe** [notepad-plus-plus/wingup#12]
Unsure if I shall have posted that into NPP project or here, but this project seemed more accurate.

I stumbled upon this:
![NPP-WinGup](https://user-images.githubusercontent.com/4251220/68932910-db5b4480-0793-11ea-84a0-e6cabf21cafd.png)

It might be the sign of something at best worrying, at worst utterly dangerous.

**Comment by chcg** [comment]
See https://github.com/gup4win/wingup/pull/23 for a fix on the garbage value for the progress value.

**Comment by donho** [comment]
This issue has been fixed.
