### ISSUE TITLE
Provide more info when checking for update

### ISSUE THREAD

**Issue by mere-human** [notepad-plus-plus/wingup#13]
### Description of the Issue
When a new version of Notepad++ is released on a site, it is not available when checking for updates from installed Notepad++.

This got asked a lot on the community forum. See recent posts:
https://community.notepad-plus-plus.org/topic/20590/updating-through-npp-occurs-very-late
https://community.notepad-plus-plus.org/topic/20592/no-update-available-but-update-is-available
And some older posts:
https://community.notepad-plus-plus.org/topic/15433/update-notepad-does-not-work
https://community.notepad-plus-plus.org/topic/15430/please-update-getdownloadurl-php
https://community.notepad-plus-plus.org/topic/16919/update-stopped-working-under-7-5-9

You may read through them, sometimes there might be interesting suggestions.

I know that the auto-update is usually triggered 1-2 weeks after the initial release, in case there are major regressions that weren’t found during the internal testing. But some of the users seem confused, so it could be better to improve the information about updates.

Also, see discussion in another issue https://github.com/notepad-plus-plus/notepad-plus-plus/issues/9393

### Steps to Reproduce the Issue

1. Prerequisite: New version of Notepad++ is released on the site (7.9.2)
2. Launch the previous version of Notepad++ (7.9.1) 
3. Open from menu _? > Update Notepad++_

### Expected Behavior
A message box with text is shown:
```
No update is available.

The auto-update may not have been activated yet.
Go to the Notepad++ official website to check for a new version?
[Cancel]   [OK]
```

Click [OK] will open the browser and lead the user to the Notepad++ Download page.

Other options:

1. A message box appears saying something like "A new version is pending approval. You can download it from the official site."
2. A message box appears saying something like "A new version is unstable. Update anyway? Yes/No"
3. Someone from the community suggested splitting the releases to be alpha, beta, and RC (and maybe stable). But this seems complicated.
4. Any other suggestions?

### Actual Behavior

A message box appears saying "No update is available":
![image](https://user-images.githubusercontent.com/9664141/104641558-9a6e0100-56b2-11eb-9017-5dce15469482.png)

### Debug Information

Notepad++ v7.9.1   (64-bit)
Build time : Nov  2 2020 - 01:07:46
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : ON
Local Conf mode : OFF
OS Name : Windows 7 Professional (64-bit) 
OS Build : 7601.24557
Current ANSI codepage : 1252
Plugins : HexEditor.dll mimeTools.dll NppConverter.dll NppExport.dll

**Comment by mere-human** [comment]
I will submit a PR for this later.

**Comment by mere-human** [comment]
Does it make more sense to show a link in the Update dialog?
Like this:
![image](https://user-images.githubusercontent.com/9664141/105616065-c5580380-5ddc-11eb-9eee-cf351bfbf4ed.png)
To me, it looks better than Yes/No option.

**Comment by donho** [comment]
@mere-human 

If it doesn't too complicated to make, yes it's better.

**Comment by mere-human** [comment]
An updated version of a dialog with a link:
![image](https://user-images.githubusercontent.com/9664141/106126166-b7e8a380-6165-11eb-9081-74050ba2335a.png)

**Comment by donho** [comment]
@mere-human 
Looks nice. Don't forget to create a PR ;)
