### ISSUE TITLE
VERY difficult to diagnose an exception in GUP.exe, with an unspecified environment TEMP variable!

### ISSUE THREAD

**Issue by jurekl** [notepad-plus-plus/wingup#16]
Today I tried to search and install the plugin for NPP. It did not manage, ever, each time the error message appeared in Wingup.
Of course, as in M$ Windows, without any details.
I had to download the sources and compile the Debug version, which with the help of Debugger vs2017 helped to determine the cause of unpleasant surprise.

After setting the TEMP environment variable, without any changes to the source code, everything started working as it should.

The case is prosaic. In the WinMain.cpp file, there is a fragment in a row 1074:

```
// Install
 std::wstring dlDest = _wgetenv(L"TEMP"); <=== Here !!!
```

String constructor with NULL ... we know how it ends :-(

It so happened that for a few days the env variableTEMP is indefinite for me (I moved the TEMP catalog to another drive!), It was enough to immobilize the functionality of GUP !! :-(

**Comment by jurekl** [comment]
It just so happened that on my computer, this variable had been undefined for several days. I think some (negligible) percentage of Windows machines may also have this situation, right? I think it is MORE important that thanks to this, I detected an unhandled exception that is a consequence of a NULL pointer in the code. I forgot the content of the error messages. They were rather stupid and not specific, like at Microsoft! Something that the program ended suddenly, as if I didn't know it myself :-(
So I checked the situation live, in Visual Studio, after compiling the debug version of gup.exe. I checked and confirmed the diagnosis that the lack of the TEMP variable causes the program to crash.
I thought this information would be useful to the developers of the program. If not, forget about this issue. Regards!

**Comment by mere-human** [comment]
@jurekl Do you have other variables set? Like `TMP` or `APPDATA`? 
This can be checked if you open `⊞ Win > cmd` and type `set`. It will show you all your environment variables.
I'm just thinking of alternatives to `TEMP`.

**Comment by jurekl** [comment]
@mere-human, thank you, I'm fine!
I explained everything in detail in the first post. While experimenting with the drive / directory for temporary files (several days ago),, I deleted the TEMP + TMP definition ... and forgot about it.
Yesterday I set its value again and thus eliminated the occurrence of NULL pointer in the gup code. Only benefits. 
However, I suggest checking the mandatory return values from API functions, like here:

`std::wstring dlDest = _wgetenv(L"TEMP");`

to avoid unpleasant surprises like in this case :-)

I'm finishing my adventure with searching for this error, I hope I helped!
Hello, best regards!

**Comment by mere-human** [comment]
> to avoid unpleasant surprises like in this case :-)

I've already came up with a fix.

> I'm finishing my adventure with searching for this error, I hope I helped!

Thank you for finding this out and reporting it here!

**Comment by mere-human** [comment]
By the way, if auto-update failed for some reason, it is always possible to download the installer manually:
https://notepad-plus-plus.org/downloads/

**Comment by jurekl** [comment]
> Thank you for finding this out and reporting it here!

Thanks for your cooperation, all the best!

**Comment by donho** [comment]
@jurekl  @mere-human 
How can I reproduce the crash?
I have removed TMP & TEMP from env : 

![image](https://user-images.githubusercontent.com/90293/131935868-3181b2d2-f88f-42a9-90bf-e0fec5f9d93d.png)


But I can still update from v8.1.3 to v8.1.4 with no problem.

**Comment by mere-human** [comment]
> How can I reproduce the crash?

See steps in PR. Use Visual Studio.

**Comment by jurekl** [comment]
Hi,
I detected the error when **trying to install the notepad ++ plugin**, not updating the NPP itself.
With the TEMP variable missing, this resulted in the errors described previously.
