### ISSUE TITLE
AppVeyor verification for WinGUP

### ISSUE THREAD

**Issue by mere-human** [notepad-plus-plus/wingup#17]
This will prevent broken builds and make the contribution easier.

**Comment by chcg** [comment]
@donho Available via https://github.com/gup4win/wingup/pull/19, just not merged until now. Maybe slightly outdated in the meantime regarding VS2017 vs. VS2019.

**Comment by donho** [comment]
@chcg 
Merged. Really sorry for forgetting merging it, since this project is not maintained anymore.
Let's focus on this forked branch if you want to work on WinGUp.

**Comment by donho** [comment]
6ff43e0607835509c6ab0dd6345b518601963f37

**Comment by mere-human** [comment]
It's gratifying to see this was finally fixed. Good job!
