### ISSUE TITLE
No translation strings for the dialog title or button

### ISSUE THREAD

**Issue by Regnander** [notepad-plus-plus/wingup#33]
The strings "Notepad++ update" and "Close" cannot be found in [english.xml](https://github.com/notepad-plus-plus/wingup/blob/master/src/translations/english.xml). Can you add them?

![](https://user-images.githubusercontent.com/17113053/218867370-ce0c8fa6-7867-48cc-b269-bdad8383ee4f.png)

**Comment by rddim** [comment]
![Image-2023-02-15-22-28-07](https://user-images.githubusercontent.com/8998791/219147099-7fbcefd5-8b35-4730-a205-5e14507b7afb.png)

And also `Update available`, `Yes`, `No` and `Never`.
This window appear when `GUP.exe` is started directly.

**Comment by conky77** [comment]
![immagine](https://user-images.githubusercontent.com/59116246/219464752-2d0be2c3-cf0b-40a0-ab23-e52750034d49.png)

and proxy setting

**Comment by Neustradamus** [comment]
@Regnander, @rddimn, @conky77: I think it is needed to create a ticket here:
- https://github.com/gup4win/wingup

**Comment by Regnander** [comment]
> I think it is needed to create a ticket here

Done, thanks!

https://github.com/gup4win/wingup/issues/49

**Comment by Neustradamus** [comment]
@donho: Thanks!

Do not forget to update upstream:
- https://github.com/gup4win/wingup
