### ISSUE TITLE
Removal of complete plugins dir

### ISSUE THREAD

**Issue by chcg** [notepad-plus-plus/wingup#6]
- right now with latest test versions of n++ and wingup for 32bit I had an issue that the complete plugin dir was removed.
- actions before were:
-- installation of jslint 0.8.3 via pluginmanager to the old path
-- removal of jstools 1.1810.3, shown in installed list, but not part of npplist

This issue needs further investigation on the really relevant action to reproduce the problem. Right now this is just a once issue.

**Comment by donho** [comment]
Fixed in 5.0.5
